<?php // -*-mode: PHP; coding:utf-8;-*-
// $Id: lang.en 2803 2014-01-17 14:25:01Z cimorrison $
//      lang.nbb.en 2015-01-18  M Thompson
// This file contains PHP code that specifies language specific strings
// The default strings come from lang.en, and anything in a locale
// specific file will overwrite the default. This is a US/UK English file.
//
//
//
//
// This file is PHP code. Treat it as such.

// Used in style.inc
$vocab_override["en"]["oars"]               = "Online Activity Recording System";


// Used in edit_entry.php

$vocab_override["en"]["namebooker"]         = "Member Name";
$vocab_override["en"]["fulldescription"]    = "Member Details";
$vocab_override["en"]["period"]             = "Shift";
$vocab_override["en"]["period_lc"]          = "shift";
$vocab_override["en"]["periods"]            = "shifts";
$vocab_override["en"]["area"]               = "Group";
$vocab_override["en"]["type"]               = "Rota Type";
$vocab_override["en"]["ctrl_click"]         = "Use Control-Click to select Multiple Types";
$vocab_override["en"]["brief_description"]  = "Member_Name";

// Used in view_entry.php
$vocab_override["en"]["description"]         = "Name";
$vocab_override["en"]["room"]                = "Roster";

// Used in edit_entry_handler.php
$vocab_override["en"]["must_set_description"] = "You must set a Member Name for the booking. Please go back and enter one.";
$vocab_override["en"]["no_rooms_selected"]    = "You must select a Roster.";

// Used in report.php
$vocab_override["en"]["report_on"]             = "Report on Shifts";
$vocab_override["en"]["match_area"]            = "Match Group";
$vocab_override["en"]["match_room"]            = "Match Roster";
$vocab_override["en"]["match_type"]            = "Match shift type";
$vocab_override["en"]["ctrl_click_type"]       = "Use Control-Click to select more than one type";
$vocab_override["en"]["match_entry"]           = "Match Member Name";
$vocab_override["en"]["match_descr"]           = "Match Member Details";
$vocab_override["en"]["csv"]                   = "CSV (download)";
$vocab_override["en"]["sum_by_descrip"]        = "Member Name";
$vocab_override["en"]["summary_header_per"]    = "Summary of (Entries) Shifts";
$vocab_override["en"]["summary_header_both"]   = "Summary of (Entries) Hours/Shifts";
$vocab_override["en"]["fulldescription_short"] = "Member Details";


// Used in help.php
$vocab_override["en"]["about_oars"]         = "About Online Activity Recording";



$vocab_override["en"]["norights"]           = "<strong>Warning</strong> - this system is operated by Northumbria Blood Bikes. <br> Unauthorised access or misuse of this system is prohibited and constitutes an offence under the Computer Misuse Act 1990.  <br> Use of, or disclosure of, any information obtained through this system without proper authorisation may lead to Northumbria Blood Bikes taking legal action against you. <br> If you are authorised to use this computer system please enter your authentication details now, otherwise please <a href='http://www.northumbriabloodbikes.org.uk'>click here to return to our public website.</a>.";

// Used in mysql.inc AND pgsql.inc

// Used in DataTables

// Entry types
 
// General



